<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
'key' => 'group_61636c62b003e',
'title' => 'Map',
'fields' => array(
array(
'key' => 'field_6163702facc13',
'label' => 'Setup',
'name' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
),
array(
'key' => 'field_616370e532005',
'label' => 'Map Type',
'name' => 'map_type',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_61636c71d48e1',
		'label' => 'Map Provider',
		'name' => 'map_provider',
		'type' => 'select',
		'instructions' => 'If you need help choosing, see our help docs! After you change this option, please update and reload the page to see the correct map loaded.',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'maplibre' => 'MapLibre',
			'mapbox' => 'Mapbox',
		),
		'default_value' => 'maplibre',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_61636d761864c',
		'label' => 'Access Token',
		'name' => 'access_token',
		'type' => 'text',
		'instructions' => 'Insert your access token here. By default, it\'s loaded from your settings, but you can remove it.',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_61636d141864b',
		'label' => 'Map Tile Style (Access Token)',
		'name' => 'map_tile_style_access_token',
		'type' => 'select',
		'instructions' => 'Differs depending if you have an access token or not.',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61636d761864c',
					'operator' => '!=empty',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'streets' => 'Streets',
			'outdoors' => 'Outdoors',
			'light' => 'Light',
			'dark' => 'Dark',
			'satellite' => 'Satellite',
			'satellite-streets' => 'Satellite Streets',
			'empty' => 'Empty',
			'open-street-map' => 'Open Street Map',
			'open-topo-map' => 'Open Topo Map',
			'cyclo-osm' => 'CyclOSM',
			'toner-stamen' => 'Toner (Stamen)',
			'watercolor-stamen' => 'Watercolor (Stamen)',
			'terrain-stamen' => 'Terrain (Stamen)',
		),
		'default_value' => 'streets',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_61636f4ed9390',
		'label' => 'Map Tile Style (No Access Token)',
		'name' => 'map_tile_style_no_access_token',
		'type' => 'select',
		'instructions' => 'Differs depending if you have an access token or not.',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61636d761864c',
					'operator' => '==empty',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'open-street-map' => 'Open Street Map',
			'open-topo-map' => 'Open Topo Map',
			'cyclo-osm' => 'CyclOSM',
			'toner-stamen' => 'Toner (Stamen)',
			'watercolor-stamen' => 'Watercolor (Stamen)',
			'terrain-stamen' => 'Terrain (Stamen)',
			'empty' => 'Empty',
		),
		'default_value' => 'open-street-map',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_616b319f75796',
		'label' => 'Custom Mapbox Style',
		'name' => 'custom_mapbox_style',
		'type' => 'text',
		'instructions' => 'Enter a style from your Mapbox account here.',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_616cc11de5b4f',
		'label' => 'Terrain',
		'name' => 'terrain',
		'type' => 'true_false',
		'instructions' => 'Add 3D terrain to the map.',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61636c71d48e1',
					'operator' => '==',
					'value' => 'mapbox',
				),
				array(
					'field' => 'field_61636d761864c',
					'operator' => '!=empty',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
),
),
array(
'key' => 'field_617c54ddda520',
'label' => 'View',
'name' => 'view',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_617c54f6da521',
		'label' => 'Initial Load',
		'name' => 'initial_load',
		'type' => 'select',
		'instructions' => 'Choose how you want to map to appear when it first loads.',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'fit-features' => 'Fit to Features',
			'manual' => 'Manual Center & Zoom',
		),
		'default_value' => 'fit-features',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_617c5543da522',
		'label' => 'Manual Latitude',
		'name' => 'manual_latitude',
		'type' => 'number',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_617c54f6da521',
					'operator' => '==',
					'value' => 'manual',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 0,
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => -90,
		'max' => 90,
		'step' => '',
	),
	array(
		'key' => 'field_617c558dda523',
		'label' => 'Manual Longitude',
		'name' => 'manual_longitude',
		'type' => 'number',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_617c54f6da521',
					'operator' => '==',
					'value' => 'manual',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 0,
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => -180,
		'max' => 180,
		'step' => '',
	),
	array(
		'key' => 'field_617c559fda524',
		'label' => 'Manual Zoom',
		'name' => 'manual_zoom',
		'type' => 'number',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_617c54f6da521',
					'operator' => '==',
					'value' => 'manual',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 0,
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => 0,
		'max' => 22,
		'step' => '',
	),
),
),
array(
'key' => 'field_616766dcb2f7e',
'label' => 'Layout',
'name' => 'layout',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6167658ddd833',
		'label' => 'Height',
		'name' => 'height',
		'type' => 'number',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '50',
			'class' => '',
			'id' => '',
		),
		'default_value' => 400,
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => 0,
		'max' => '',
		'step' => '',
	),
	array(
		'key' => 'field_616765acdd834',
		'label' => 'Height Units',
		'name' => 'height_units',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '15',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'px' => 'px',
			'%' => '%',
		),
		'default_value' => 'px',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_616765d4dd835',
		'label' => 'Width',
		'name' => 'width',
		'type' => 'number',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '50',
			'class' => '',
			'id' => '',
		),
		'default_value' => 100,
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => 0,
		'max' => '',
		'step' => '',
	),
	array(
		'key' => 'field_616765e8dd836',
		'label' => 'Width Units',
		'name' => 'width_units',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '15',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'px' => 'px',
			'%' => '%',
		),
		'default_value' => '%',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_61a4300dd751a',
		'label' => 'Full page',
		'name' => 'full_page',
		'type' => 'true_false',
		'instructions' => 'Selecting this option will make your map as high as the user\'s screen and as wide as your theme allows (100%).',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_61a43130873b9',
		'label' => 'Ignore Container',
		'name' => 'ignore_container',
		'type' => 'true_false',
		'instructions' => 'Ignore your theme limits and force the map to be the full width of the user\'s screen.',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61a4300dd751a',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
),
),
array(
'key' => 'field_61637af50e99e',
'label' => 'Features',
'name' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
),
array(
'key' => 'field_61637b0892e4a',
'label' => 'Locations',
'name' => 'locations',
'type' => 'post_object',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'post_type' => array(
	0 => 'mapster-wp-location',
),
'taxonomy' => '',
'allow_null' => 0,
'multiple' => 1,
'return_format' => 'object',
'ui' => 1,
),
array(
'key' => 'field_61637b2fb1cc2',
'label' => 'Lines',
'name' => 'lines',
'type' => 'post_object',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'post_type' => array(
	0 => 'mapster-wp-line',
),
'taxonomy' => '',
'allow_null' => 0,
'multiple' => 1,
'return_format' => 'object',
'ui' => 1,
),
array(
'key' => 'field_61637b3fb1cc3',
'label' => 'Polygons',
'name' => 'polygons',
'type' => 'post_object',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'post_type' => array(
	0 => 'mapster-wp-polygon',
),
'taxonomy' => '',
'allow_null' => 0,
'multiple' => 1,
'return_format' => 'object',
'ui' => 1,
),
array(
'key' => 'field_6186d543b6f7f',
'label' => 'Add by Category',
'name' => 'add_by_category',
'type' => 'taxonomy',
'instructions' => 'Try not to add features twice -- you may encounter errors or duplications.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'taxonomy' => 'wp-map-category',
'field_type' => 'multi_select',
'allow_null' => 0,
'add_term' => 0,
'save_terms' => 0,
'load_terms' => 0,
'return_format' => 'id',
'multiple' => 0,
),
array(
'key' => 'field_616f6b591ebac',
'label' => 'Circle Clustering',
'name' => 'circle_clustering',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_6178dcc22f265',
'label' => 'Label & Icon Clustering',
'name' => 'label_icon_clustering',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_61636fe6af17b',
'label' => 'Interactivity',
'name' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
),
array(
'key' => 'field_6167667ab2f7c',
'label' => 'Zoom on Scroll',
'name' => 'zoom_on_scroll',
'type' => 'true_false',
'instructions' => 'Allow user to zoom with the mouse wheel. This will not change the editor map, only the map presented on the front-end of your site.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 1,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_616766a3b2f7d',
'label' => 'Interactivity',
'name' => 'interactivity',
'type' => 'true_false',
'instructions' => 'Enable or disable interaction completely on the map. This will not change the editor map, only the map presented on the front-end of your site.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 1,
'ui' => 1,
'ui_on_text' => 'Enable',
'ui_off_text' => 'Disable',
),
array(
'key' => 'field_61636fb2af179',
'label' => 'Controls',
'name' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
),
array(
'key' => 'field_616768aa0ad63',
'label' => 'Zoom Control',
'name' => 'zoom_control',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_61676748f4045',
		'label' => 'Enable',
		'name' => 'enable',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 1,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_616767b7f4049',
		'label' => 'Position',
		'name' => 'position',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61676748f4045',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'top-right' => 'Top Right',
			'top-left' => 'Top Left',
			'bottom-right' => 'Bottom Right',
			'bottom-left' => 'Bottom Left',
		),
		'default_value' => 'top-right',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
),
),
array(
'key' => 'field_616768d90ad64',
'label' => 'Geocoder Control',
'name' => 'geocoder_control',
'type' => 'group',
'instructions' => 'This allows users to search for an address. Requires a Mapbox token.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6167685d51239',
		'label' => 'Enable',
		'name' => 'enable',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_616768875123a',
		'label' => 'Position',
		'name' => 'position',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_6167685d51239',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'top-right' => 'Top Right',
			'top-left' => 'Top Left',
			'bottom-right' => 'Bottom Right',
			'bottom-left' => 'Bottom Left',
		),
		'default_value' => 'top-left',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_61676cf907199',
		'label' => 'Limit Results',
		'name' => 'limit_results',
		'type' => 'text',
		'instructions' => 'Limit results to specific countries. Use 2-letter country codes, separated by commas.',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_6167685d51239',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
),
),
array(
'key' => 'field_616cc35dcbbe0',
'label' => '3D Control',
'name' => '3d_control',
'type' => 'group',
'instructions' => 'Adds a button that allows the user to easily switch to a 3D tilted view.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_616cc386cbbe1',
		'label' => 'Enable',
		'name' => 'enable',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_616cc39fcbbe2',
		'label' => 'Position',
		'name' => 'position',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_616cc386cbbe1',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'top-right' => 'Top Right',
			'top-left' => 'Top Left',
			'bottom-right' => 'Bottom Right',
			'bottom-left' => 'Bottom Left',
		),
		'default_value' => 'top-right',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
),
),
array(
'key' => 'field_6167763ea63ab',
'label' => 'Directions Control',
'name' => 'directions_control',
'type' => 'group',
'instructions' => 'Requires a Mapbox token.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_61677651a63ac',
		'label' => 'Enable',
		'name' => 'enable',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_6167768aa63ad',
		'label' => 'Position',
		'name' => 'position',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61677651a63ac',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'top-right' => 'Top Right',
			'top-left' => 'Top Left',
			'bottom-right' => 'Bottom Right',
			'bottom-left' => 'Bottom Left',
		),
		'default_value' => 'top-left',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_616776a6a63ae',
		'label' => 'Units',
		'name' => 'units',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61677651a63ac',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'imperial' => 'Imperial',
			'metric' => 'Metric',
		),
		'default_value' => 'imperial',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_616776cba63af',
		'label' => 'Default Type',
		'name' => 'default_type',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61677651a63ac',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'mapbox/driving-traffic' => 'Driving Traffic',
			'mapbox/driving' => 'Driving',
			'mapbox/walking' => 'Walking',
			'mapbox/cycling' => 'Cycling',
		),
		'default_value' => 'mapbox/driving-traffic',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_61677707a63b0',
		'label' => 'Placeholder Text',
		'name' => 'placeholder_text',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61677651a63ac',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 'Enter a starting location',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
),
),
array(
'key' => 'field_6167695619e0c',
'label' => 'Geolocation Control (User Tracking)',
'name' => 'geolocation_control',
'type' => 'group',
'instructions' => 'This adds a button to the map so users can see their own location (requires HTTPS).',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6167695619e0d',
		'label' => 'Enable',
		'name' => 'enable',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_6167695619e0e',
		'label' => 'Position',
		'name' => 'position',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_6167695619e0d',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'top-right' => 'Top Right',
			'top-left' => 'Top Left',
			'bottom-right' => 'Bottom Right',
			'bottom-left' => 'Bottom Left',
		),
		'default_value' => 'top-right',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
),
),
array(
'key' => 'field_6167697d19e0f',
'label' => 'Fullscreen Control',
'name' => 'fullscreen_control',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6167697d19e10',
		'label' => 'Enable',
		'name' => 'enable',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_6167697d19e11',
		'label' => 'Position',
		'name' => 'position',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_6167697d19e10',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'top-right' => 'Top Right',
			'top-left' => 'Top Left',
			'bottom-right' => 'Bottom Right',
			'bottom-left' => 'Bottom Left',
		),
		'default_value' => 'top-right',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
),
),
array(
'key' => 'field_6167693919e09',
'label' => 'Scale Control',
'name' => 'scale_control',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6167693919e0a',
		'label' => 'Enable',
		'name' => 'enable',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_6167693919e0b',
		'label' => 'Position',
		'name' => 'position',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_6167693919e0a',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'top-right' => 'Top Right',
			'top-left' => 'Top Left',
			'bottom-right' => 'Bottom Right',
			'bottom-left' => 'Bottom Left',
		),
		'default_value' => 'bottom-right',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
),
),
array(
'key' => 'field_616372615390b',
'label' => 'Filter & List',
'name' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
),
array(
'key' => 'field_616769a697bdd',
'label' => 'Filter',
'name' => 'filter',
'type' => 'group',
'instructions' => 'Enabling filters will allow users to search through and/or change the visibility of features on your map.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_61676ae545cb3',
		'label' => 'Custom Search Filter',
		'name' => 'custom_search_filter',
		'type' => 'group',
		'instructions' => 'This will allow a text search (using the names and popup text you\'ve added to features) and present results to users in a clickable dropdown.',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'layout' => 'block',
		'sub_fields' => array(
			array(
				'key' => 'field_61676a4e45cb1',
				'label' => 'Enable',
				'name' => 'enable',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_61676abb45cb2',
				'label' => 'Include Geocoder',
				'name' => 'include_geocoder',
				'type' => 'true_false',
				'instructions' => 'This will allow users to search both addresses and your feature information at once. Requires a Mapbox token.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_61676a4e45cb1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '55',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_61676ed29d539',
				'label' => 'Limit Results',
				'name' => 'limit_results',
				'type' => 'text',
				'instructions' => 'Limit results to specific countries. Use 2-letter country codes, separated by commas.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_61676abb45cb2',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '55',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_61676ef49d53a',
				'label' => 'Position',
				'name' => 'position',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_61676a4e45cb1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '55',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'top-right' => 'Top Right',
					'top-left' => 'Top Left',
					'bottom-right' => 'Bottom Right',
					'bottom-left' => 'Bottom Left',
				),
				'default_value' => 'top-left',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
	),
	array(
		'key' => 'field_61676b7379238',
		'label' => 'Filter Dropdown',
		'name' => 'filter_dropdown',
		'type' => 'group',
		'instructions' => 'Present map features to users in a clickable dropdown list.',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'layout' => 'block',
		'sub_fields' => array(
			array(
				'key' => 'field_61676ba779239',
				'label' => 'Enable',
				'name' => 'enable',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_61676bb57923a',
				'label' => 'Position',
				'name' => 'position',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_61676ba779239',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'top-right' => 'Top Right',
					'bottom-right' => 'Bottom Right',
					'top-left' => 'Top Left',
					'bottom-left' => 'Bottom Left',
					'above-map' => 'Above Map',
					'below-map' => 'Below Map',
				),
				'default_value' => 'top-right',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
	),
	array(
		'key' => 'field_61676c30af8b3',
		'label' => 'Category Filter',
		'name' => 'category_filter',
		'type' => 'group',
		'instructions' => 'Add a control panel that lists the categories of your features as toggles. All categories attached to your features will be included.',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'layout' => 'block',
		'sub_fields' => array(
			array(
				'key' => 'field_61676c53af8b4',
				'label' => 'Enable',
				'name' => 'enable',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_616c512ca1b1c',
				'label' => 'Category Display',
				'name' => 'category_display',
				'type' => 'select',
				'instructions' => 'You can add a color or icon to each category in the Categories section, and have them appear beside the category in the list.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_61676c53af8b4',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '55',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'none' => 'None',
					'colors' => 'Colors',
					'icons' => 'icons',
				),
				'default_value' => 'none',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_616c5174a1b1d',
				'label' => 'Checkbox Display',
				'name' => 'checkbox_display',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_61676c53af8b4',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '55',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'switch' => 'Switch',
					'checkbox' => 'Checkbox',
				),
				'default_value' => 'switch',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_61676c5daf8b5',
				'label' => 'Position',
				'name' => 'position',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_61676c53af8b4',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '55',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'top-right' => 'Top Right',
					'top-left' => 'Top Left',
					'bottom-right' => 'Bottom Right',
					'bottom-left' => 'Bottom Left',
				),
				'default_value' => 'top-right',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
	),
),
),
array(
'key' => 'field_61676dc862fc5',
'label' => 'List',
'name' => 'list',
'type' => 'group',
'instructions' => 'This will create a clickable list of all your features -- perfect for a Store Locator.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_61676dd662fc6',
		'label' => 'Enable',
		'name' => 'enable',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_616c57feabfda',
		'label' => 'Include Geocoder',
		'name' => '',
		'type' => 'message',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61676dd662fc6',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => 'To include a geocoder for address searching, go to the "Controls" tab and add a Geocoder Control. It will interact with the list using the options below.',
		'new_lines' => 'wpautop',
		'esc_html' => 0,
	),
	array(
		'key' => 'field_616c5809abfdb',
		'label' => 'Sort by Distance',
		'name' => 'sort_by_distance',
		'type' => 'true_false',
		'instructions' => 'Sorts by the distance of the current map\'s center (adjusting as user searches or moves).',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61676dd662fc6',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_616c584aabfdc',
		'label' => 'Show Distance',
		'name' => 'show_distance',
		'type' => 'true_false',
		'instructions' => 'Show distance from the map center to the shape\'s center.',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61676dd662fc6',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_616caf7bbfac5',
		'label' => 'Units',
		'name' => 'units',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61676dd662fc6',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'imperial' => 'Imperial',
			'metric' => 'Metric',
		),
		'default_value' => 'imperial',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_61676e4062fc7',
		'label' => 'Number of Locations',
		'name' => 'number_of_locations',
		'type' => 'number',
		'instructions' => 'Number of locations listed on each page of results.',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61676dd662fc6',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 5,
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => 0,
		'max' => '',
		'step' => '',
	),
	array(
		'key' => 'field_61676e6862fc8',
		'label' => 'Position',
		'name' => 'position',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61676dd662fc6',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'top-right' => 'Top Right',
			'top-left' => 'Top Left',
			'bottom-right' => 'Bottom Right',
			'bottom-left' => 'Bottom Left',
		),
		'default_value' => 'top-left',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
),
),
array(
'key' => 'field_61ae3c8d5599d',
'label' => 'Custom',
'name' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
),
array(
'key' => 'field_61ae3ca05599e',
'label' => 'Javascript',
'name' => 'javascript',
'type' => 'text',
'instructions' => 'Add the name of a Javascript function you want to run after the map initializes. This function must be global. It will be given a "map" variable and a "features" variable, with which you can create more custom functionality or sidebar lists, etc.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
),
'location' => array(
array(
array(
	'param' => 'post_type',
	'operator' => '==',
	'value' => 'mapster-wp-map',
),
),
),
'menu_order' => 0,
'position' => 'acf_after_title',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_6168cc95e9e68',
'title' => 'Map Categories',
'fields' => array(
array(
'key' => 'field_6168ccb0939fe',
'label' => 'Color',
'name' => 'color',
'type' => 'color_picker',
'instructions' => 'Color swatch will display in map filters.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'default_value' => '',
'enable_opacity' => 0,
'return_format' => 'string',
),
array(
'key' => 'field_6168ce2b0cba5',
'label' => 'Icon',
'name' => 'icon',
'type' => 'image',
'instructions' => 'Icon will display in map filters.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'return_format' => 'array',
'preview_size' => 'medium',
'library' => 'all',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
),
),
'location' => array(
array(
array(
	'param' => 'taxonomy',
	'operator' => '==',
	'value' => 'wp-map-category',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_616377d62836b',
'title' => 'Map Line',
'fields' => array(
array(
'key' => 'field_616377f9af36c',
'label' => 'Line',
'name' => 'line',
'type' => 'mapster-map',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'mapster-draw-type-point' => 0,
'mapster-draw-type-linestring' => 1,
'mapster-draw-type-polygon' => 0,
'mapster-draw-type-multiple' => 0,
'default_value' => '{ "type" : "FeatureCollection", "features" : [] }',
),
array(
'key' => 'field_616378425c334',
'label' => 'Color',
'name' => 'color',
'type' => 'color_picker',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'default_value' => '',
'enable_opacity' => 0,
'return_format' => 'string',
),
array(
'key' => 'field_6163780caf36d',
'label' => 'Width',
'name' => 'width',
'type' => 'number',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'default_value' => 5,
'placeholder' => '',
'prepend' => '',
'append' => 'px',
'min' => 0,
'max' => '',
'step' => '',
),
array(
'key' => 'field_6163782e5c333',
'label' => 'Opacity',
'name' => 'opacity',
'type' => 'number',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'default_value' => 100,
'placeholder' => '',
'prepend' => '',
'append' => '%',
'min' => 0,
'max' => 100,
'step' => 1,
),
array(
'key' => 'field_616378845c338',
'label' => 'Dashed Line',
'name' => 'dashed_line',
'type' => 'true_false',
'instructions' => 'Dashed lines only work using Mapbox maps.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_616378b9a2d93',
'label' => 'Dash Properties',
'name' => 'dash_properties',
'type' => 'group',
'instructions' => 'See the documentation for help on setting these values.',
'required' => 0,
'conditional_logic' => array(
	array(
		array(
			'field' => 'field_616378845c338',
			'operator' => '==',
			'value' => '1',
		),
	),
),
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6163784f5c335',
		'label' => 'Dash Length',
		'name' => 'dash_length',
		'type' => 'number',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 2,
		'placeholder' => '',
		'prepend' => '',
		'append' => 'px',
		'min' => '',
		'max' => '',
		'step' => '',
	),
	array(
		'key' => 'field_6163786d5c337',
		'label' => 'Gap Length',
		'name' => 'gap_length',
		'type' => 'number',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 1,
		'placeholder' => '',
		'prepend' => '',
		'append' => 'px',
		'min' => '',
		'max' => '',
		'step' => '',
	),
),
),
),
'location' => array(
array(
array(
	'param' => 'post_type',
	'operator' => '==',
	'value' => 'mapster-wp-line',
),
),
),
'menu_order' => 0,
'position' => 'acf_after_title',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_6163732e0426e',
'title' => 'Map Location',
'fields' => array(
array(
'key' => 'field_6163b9b4b4ddc',
'label' => 'Location',
'name' => 'location',
'type' => 'mapster-map',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'mapster-draw-type-point' => 1,
'mapster-draw-type-linestring' => 0,
'mapster-draw-type-polygon' => 0,
'mapster-draw-type-multiple' => 0,
'default_value' => '{ "type" : "FeatureCollection", "features" : [] }',
),
array(
'key' => 'field_61637347292a4',
'label' => 'Location Style',
'name' => 'location_style',
'type' => 'select',
'instructions' => 'Choose how you want the location to be displayed: as a circle, a classic marker, text, or an icon.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'choices' => array(
	'circle' => 'Circle',
	'marker' => 'Marker',
	'label' => 'Label & Icon',
),
'default_value' => 'marker',
'allow_null' => 0,
'multiple' => 0,
'ui' => 0,
'return_format' => 'value',
'ajax' => 0,
'placeholder' => '',
),
array(
'key' => 'field_616373e5cca5e',
'label' => 'Circle',
'name' => 'circle',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => array(
	array(
		array(
			'field' => 'field_61637347292a4',
			'operator' => '==',
			'value' => 'circle',
		),
	),
),
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'sub_fields' => array(
	array(
		'key' => 'field_6163740b2db31',
		'label' => 'Radius',
		'name' => 'radius',
		'type' => 'number',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 5,
		'placeholder' => '',
		'prepend' => '',
		'append' => 'px',
		'min' => 0,
		'max' => '',
		'step' => '0.1',
	),
	array(
		'key' => 'field_6163743632bb4',
		'label' => 'Opacity',
		'name' => 'opacity',
		'type' => 'number',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 100,
		'placeholder' => '',
		'prepend' => '',
		'append' => '%',
		'min' => 0,
		'max' => 100,
		'step' => 1,
	),
	array(
		'key' => 'field_6163749bd02bd',
		'label' => 'Color',
		'name' => 'color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => '#000000',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_616374c0d02bf',
		'label' => 'Border Width',
		'name' => 'stroke-width',
		'type' => 'number',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 0,
		'placeholder' => '',
		'prepend' => '',
		'append' => 'px',
		'min' => 0,
		'max' => '',
		'step' => '0.1',
	),
	array(
		'key' => 'field_616374e7d02c0',
		'label' => 'Border Color',
		'name' => 'stroke-color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_616507d400234',
		'label' => 'Border Opacity',
		'name' => 'stroke-opacity',
		'type' => 'number',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 100,
		'placeholder' => '',
		'prepend' => '',
		'append' => '%',
		'min' => 0,
		'max' => 100,
		'step' => 1,
	),
),
'layout' => 'block',
),
array(
'key' => 'field_6163751088e44',
'label' => 'Marker',
'name' => 'marker',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => array(
	array(
		array(
			'field' => 'field_61637347292a4',
			'operator' => '==',
			'value' => 'marker',
		),
	),
),
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_61637538a4710',
		'label' => 'Image',
		'name' => '',
		'type' => 'message',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'message' => 'To use a custom marker image, select the "Icon & Text" Location Style above.',
		'new_lines' => 'wpautop',
		'esc_html' => 0,
	),
	array(
		'key' => 'field_616375cc16796',
		'label' => 'Color',
		'name' => 'color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => '#000000',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_6163755da4711',
		'label' => 'Scale',
		'name' => 'scale',
		'type' => 'number',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 100,
		'placeholder' => '',
		'prepend' => '',
		'append' => '%',
		'min' => 0,
		'max' => '',
		'step' => 1,
	),
	array(
		'key' => 'field_616375ff7b4e4',
		'label' => 'Rotation',
		'name' => 'rotation',
		'type' => 'number',
		'instructions' => '',
		'required' => 1,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'default_value' => 0,
		'placeholder' => '',
		'prepend' => '',
		'append' => '°',
		'min' => 0,
		'max' => 360,
		'step' => 1,
	),
	array(
		'key' => 'field_6164674824f6b',
		'label' => 'Anchor',
		'name' => 'anchor',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '55',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'center' => 'Center',
			'top' => 'Top',
			'bottom' => 'Bottom',
			'left' => 'Left',
			'right' => 'Right',
			'top-left' => 'Top Left',
			'top-right' => 'Top Right',
			'bottom-left' => 'Bottom Left',
			'bottom-right' => 'Bottom Right',
		),
		'default_value' => 'center',
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
),
),
array(
'key' => 'field_61637642c8191',
'label' => 'Label',
'name' => 'label',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => array(
	array(
		array(
			'field' => 'field_61637347292a4',
			'operator' => '==',
			'value' => 'label',
		),
	),
),
'wrapper' => array(
	'width' => '50',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6165137947bb0',
		'label' => 'Label On',
		'name' => 'label_on',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_616513aa47bb1',
		'label' => 'Text Properties',
		'name' => 'text_properties',
		'type' => 'group',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_6165137947bb0',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'layout' => 'block',
		'sub_fields' => array(
			array(
				'key' => 'field_616376581a4fb',
				'label' => 'Label Text',
				'name' => 'text-field',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Label',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6163770ad6e84',
				'label' => 'Font',
				'name' => 'text-font',
				'type' => 'select',
				'instructions' => 'By default, only Open Sans will work in a Mapbox Style. Other fonts will work from custom tile sources. If you want a font in your Mapbox map, you must load it in the Mapbox Style Editor.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Open Sans Regular' => 'Open Sans',
					'Open Sans Bold' => 'Open Sans Bold',
					'Open Sans Italic' => 'Open Sans Italic',
					'Klokantech Noto Sans Regular' => 'Noto Sans',
					'Klokantech Noto Sans Bold' => 'Noto Sans Bold',
					'Klokantech Noto Sans Italic' => 'Noto Sans Italic',
					'Metropolis' => 'Metropolis',
					'Metropolis Bold' => 'Metropolis Bold',
					'Metropolis Regular Italic' => 'Metropolis Italic',
				),
				'default_value' => 'Open Sans',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_6163767f1a4fc',
				'label' => 'Font Size',
				'name' => 'text-size',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 16,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
				'min' => 0,
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_616376b8d6e81',
				'label' => 'Color',
				'name' => 'text-color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_616376d1d6e82',
				'label' => 'Opacity',
				'name' => 'text-opacity',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 100,
				'placeholder' => '',
				'prepend' => '',
				'append' => '%',
				'min' => 0,
				'max' => 100,
				'step' => 1,
			),
			array(
				'key' => 'field_616376f3d6e83',
				'label' => 'Rotation',
				'name' => 'text-rotate',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '°',
				'min' => 0,
				'max' => 360,
				'step' => 1,
			),
			array(
				'key' => 'field_6165280fe8593',
				'label' => 'Position X',
				'name' => 'text-translate-x',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
				'min' => '',
				'max' => '',
				'step' => '0.1',
			),
			array(
				'key' => 'field_61652812e8594',
				'label' => 'Position Y',
				'name' => 'text-translate-y',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
				'min' => '',
				'max' => '',
				'step' => '0.1',
			),
			array(
				'key' => 'field_61637726d6e85',
				'label' => 'Outline Width',
				'name' => 'text-halo-width',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 1,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => '',
				'step' => '0.1',
			),
			array(
				'key' => 'field_6163774eaeba0',
				'label' => 'Outline Color',
				'name' => 'text-halo-color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#FFFFFF',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_61637761aeba1',
				'label' => 'Outline Blur',
				'name' => 'text-halo-blur',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 50,
				'placeholder' => '',
				'prepend' => '',
				'append' => '%',
				'min' => 0,
				'max' => 100,
				'step' => 1,
			),
		),
	),
),
),
array(
'key' => 'field_61651d590c6be',
'label' => 'Icon',
'name' => 'icon',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => array(
	array(
		array(
			'field' => 'field_61637347292a4',
			'operator' => '==',
			'value' => 'label',
		),
	),
),
'wrapper' => array(
	'width' => '50',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_61651d740c6bf',
		'label' => 'Icon On',
		'name' => 'icon_on',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_61651d9bf95dc',
		'label' => 'Icon Properties',
		'name' => 'icon_properties',
		'type' => 'group',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_61651d740c6bf',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'layout' => 'block',
		'sub_fields' => array(
			array(
				'key' => 'field_61651da7f95dd',
				'label' => 'Image',
				'name' => 'icon-image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => 'png,jpeg,jpg,gif',
			),
			array(
				'key' => 'field_6165211f02ad4',
				'label' => 'Scale',
				'name' => 'icon-size',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 100,
				'placeholder' => '',
				'prepend' => '',
				'append' => '%',
				'min' => 0,
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'field_6165216202ad5',
				'label' => 'Opacity',
				'name' => 'icon-opacity',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 100,
				'placeholder' => '',
				'prepend' => '',
				'append' => '%',
				'min' => 0,
				'max' => 100,
				'step' => '',
			),
			array(
				'key' => 'field_616522bd02ad8',
				'label' => 'Rotation',
				'name' => 'icon-rotate',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '°',
				'min' => 0,
				'max' => 360,
				'step' => 1,
			),
			array(
				'key' => 'field_6165218102ad6',
				'label' => 'Position X',
				'name' => 'icon-translate-x',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
				'min' => '',
				'max' => '',
				'step' => '0.1',
			),
			array(
				'key' => 'field_6165229802ad7',
				'label' => 'Position Y',
				'name' => 'icon-translate-y',
				'type' => 'number',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'px',
				'min' => '',
				'max' => '',
				'step' => '0.1',
			),
			array(
				'key' => 'field_616cb97fcb230',
				'label' => 'Anchor',
				'name' => 'icon-anchor',
				'type' => 'select',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'center' => 'Center',
					'left' => 'Left',
					'right' => 'Right',
					'top' => 'Top',
					'bottom' => 'Bottom',
					'top-left' => 'Top Left',
					'top-right' => 'Top Right',
					'bottom-left' => 'Bottom Left',
					'bottom-right' => 'Bottom Right',
				),
				'default_value' => 'center',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
	),
),
),
),
'location' => array(
array(
array(
	'param' => 'post_type',
	'operator' => '==',
	'value' => 'mapster-wp-location',
),
),
),
'menu_order' => 0,
'position' => 'acf_after_title',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_616379566202f',
'title' => 'Map Polygon',
'fields' => array(
array(
'key' => 'field_61637961f8c23',
'label' => 'Polygon',
'name' => 'polygon',
'type' => 'mapster-map',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'mapster-draw-type-point' => 0,
'mapster-draw-type-linestring' => 0,
'mapster-draw-type-polygon' => 1,
'mapster-draw-type-multiple' => 0,
'default_value' => '{ "type" : "FeatureCollection", "features" : [] }',
),
array(
'key' => 'field_61637967f8c24',
'label' => 'Color',
'name' => 'color',
'type' => 'color_picker',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'default_value' => '#0e1b82',
'enable_opacity' => 0,
'return_format' => 'string',
),
array(
'key' => 'field_61637980f8c25',
'label' => 'Opacity',
'name' => 'opacity',
'type' => 'number',
'instructions' => '',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'default_value' => 75,
'placeholder' => '',
'prepend' => '',
'append' => '%',
'min' => 0,
'max' => 100,
'step' => 1,
),
array(
'key' => 'field_6169fb5075f7f',
'label' => 'Outline Color',
'name' => 'outline-color',
'type' => 'color_picker',
'instructions' => 'Make this transparent if you don\'t want it visible.',
'required' => 1,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'default_value' => 'rgba(0, 0, 0, 0)',
'enable_opacity' => 1,
'return_format' => 'string',
),
),
'location' => array(
array(
array(
	'param' => 'post_type',
	'operator' => '==',
	'value' => 'mapster-wp-polygon',
),
),
),
'menu_order' => 0,
'position' => 'acf_after_title',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_6168be3bc0b53',
'title' => 'Mapster Settings',
'fields' => array(
array(
'key' => 'field_6168be7458083',
'label' => 'Default Access Token',
'name' => 'default_access_token',
'type' => 'text',
'instructions' => 'Enter your Mapbox Access Token. Not required for MapLibre maps.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '100',
	'class' => '',
	'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_6168db6fdbb0d',
'label' => 'Gutenberg Editor',
'name' => 'gutenberg_editor',
'type' => 'true_false',
'instructions' => 'Enable or disable the Gutenberg editor on maps, lines, locations, and polygons.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => 'Enable',
'ui_off_text' => 'Disable',
),
array(
'key' => 'field_6168e08fc684b',
'label' => 'Public Pages',
'name' => 'public_pages',
'type' => 'group',
'instructions' => 'Enable or disable map post types from being publicly accessible as standalone pages on your site.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '100',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6168e0c0c684c',
		'label' => 'Maps',
		'name' => 'maps',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 1,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_6168e0cdc684d',
		'label' => 'Locations',
		'name' => 'locations',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 1,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_6168e0d7c684e',
		'label' => 'Lines',
		'name' => 'lines',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 1,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array(
		'key' => 'field_6168e0dcc684f',
		'label' => 'Polygons',
		'name' => 'polygons',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 1,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
),
),
),
'location' => array(
array(
array(
	'param' => 'post_type',
	'operator' => '==',
	'value' => 'mapster-wp-settings',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_6169ff23a6e6d',
'title' => 'Popup Style',
'fields' => array(
array(
'key' => 'field_616a029963383',
'label' => 'Preview',
'name' => '',
'type' => 'message',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '50',
	'class' => '',
	'id' => '',
),
'message' => 'Test out how your popup looks on this map!
<div class="button button-primary">Open Popup</div>
<div id="map"></div>',
'new_lines' => 'wpautop',
'esc_html' => 0,
),
array(
'key' => 'field_616a0768a7f41',
'label' => 'Preview Content',
'name' => '_copy',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '50',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_616a02f694f0b',
		'label' => 'Header Text Preview',
		'name' => 'header_text_preview',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '100',
			'class' => '',
			'id' => '',
		),
		'default_value' => 'Sample Header',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_616a031894f0d',
		'label' => 'Content Preview',
		'name' => 'content_preview',
		'type' => 'textarea',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '100',
			'class' => '',
			'id' => '',
		),
		'default_value' => 'Sample content in a single paragraph.',
		'placeholder' => '',
		'maxlength' => '',
		'rows' => 5,
		'new_lines' => '',
	),
	array(
		'key' => 'field_616a0739c7606',
		'label' => 'Button Text Preview',
		'name' => 'button_text_preview',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '100',
			'class' => '',
			'id' => '',
		),
		'default_value' => 'Sample Button',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
),
),
array(
'key' => 'field_616a129681262',
'label' => 'Layout',
'name' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
),
array(
'key' => 'field_616a12538125e',
'label' => 'Enable Header',
'name' => 'enable_header',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 1,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_616a58e080e71',
'label' => 'Enable Image',
'name' => 'enable_image',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 1,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_616a58f480e72',
'label' => 'Image Height',
'name' => 'image_height',
'type' => 'number',
'instructions' => '',
'required' => 0,
'conditional_logic' => array(
	array(
		array(
			'field' => 'field_616a58e080e71',
			'operator' => '==',
			'value' => '1',
		),
	),
),
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'default_value' => 50,
'placeholder' => '',
'prepend' => '',
'append' => 'px',
'min' => 0,
'max' => '',
'step' => '',
),
array(
'key' => 'field_616a12668125f',
'label' => 'Enable Body',
'name' => 'enable_body',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 1,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_616a127281260',
'label' => 'Enable Footer',
'name' => 'enable_footer',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 1,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_616a127b81261',
'label' => 'Enable Pointer',
'name' => 'enable_pointer',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 1,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_616a01a206a3a',
'label' => 'Background Colors',
'name' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
),
array(
'key' => 'field_6169ff4ee9eeb',
'label' => 'Background',
'name' => 'background',
'type' => 'color_picker',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'default_value' => '#FFFFFF',
'enable_opacity' => 1,
'return_format' => 'string',
),
array(
'key' => 'field_6169ff66e9eec',
'label' => 'Header',
'name' => 'header',
'type' => 'color_picker',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'default_value' => '#FFFFFF',
'enable_opacity' => 1,
'return_format' => 'string',
),
array(
'key' => 'field_6169ffa8e9eed',
'label' => 'Body',
'name' => 'body',
'type' => 'color_picker',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'default_value' => '#FFFFFF',
'enable_opacity' => 1,
'return_format' => 'string',
),
array(
'key' => 'field_6169ffb4e9eee',
'label' => 'Footer',
'name' => 'footer',
'type' => 'color_picker',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'default_value' => '#FFFFFF',
'enable_opacity' => 1,
'return_format' => 'string',
),
array(
'key' => 'field_6169ffc2e9eef',
'label' => 'Button',
'name' => 'button',
'type' => 'color_picker',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'default_value' => '#2271b1',
'enable_opacity' => 1,
'return_format' => 'string',
),
array(
'key' => 'field_6169ffd1e9ef0',
'label' => 'Pointer',
'name' => 'pointer',
'type' => 'color_picker',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'default_value' => '#FFFFFF',
'enable_opacity' => 1,
'return_format' => 'string',
),
array(
'key' => 'field_616a01c806a3c',
'label' => 'Text',
'name' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
),
array(
'key' => 'field_616a0ec000da7',
'label' => 'Align',
'name' => 'align',
'type' => 'select',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'choices' => array(
	'left' => 'Left',
	'center' => 'Center',
	'right' => 'Right',
),
'default_value' => 'none',
'allow_null' => 0,
'multiple' => 0,
'ui' => 0,
'return_format' => 'value',
'ajax' => 0,
'placeholder' => '',
),
array(
'key' => 'field_6169fff1e9ef2',
'label' => 'Header Text',
'name' => 'header_text',
'type' => 'color_picker',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'default_value' => '#000000',
'enable_opacity' => 1,
'return_format' => 'string',
),
array(
'key' => 'field_616a000ae9ef3',
'label' => 'Body Text',
'name' => 'body_text',
'type' => 'color_picker',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'default_value' => '#000000',
'enable_opacity' => 1,
'return_format' => 'string',
),
array(
'key' => 'field_616a0018e9ef4',
'label' => 'Button Text',
'name' => 'button_text',
'type' => 'color_picker',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'default_value' => '#FFFFFF',
'enable_opacity' => 0,
'return_format' => 'string',
),
array(
'key' => 'field_616a01dd06a3d',
'label' => 'CSS',
'name' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
),
array(
'key' => 'field_616a00d9c802e',
'label' => 'Popup Class',
'name' => 'popup_class',
'type' => 'text',
'instructions' => 'Enter a custom class you can use for adding CSS styles.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_616a5d2b3c357',
'label' => 'Use Custom CSS',
'name' => 'use_custom_css',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_616a0093c802d',
'label' => 'CSS Editor',
'name' => 'css_editor',
'type' => 'textarea',
'instructions' => 'Only edit this if you understand CSS and the relevant classes! The default CSS on load is included here.',
'required' => 0,
'conditional_logic' => array(
	array(
		array(
			'field' => 'field_616a5d2b3c357',
			'operator' => '==',
			'value' => '1',
		),
	),
),
'wrapper' => array(
	'width' => '',
	'class' => 'mapster-css-editor',
	'id' => '',
),
'default_value' => '',
'placeholder' => '',
'maxlength' => '',
'rows' => 20,
'new_lines' => '',
),
array(
'key' => 'field_616a07d025da2',
'label' => 'Options',
'name' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
),
array(
'key' => 'field_616a084925da7',
'label' => 'Max Width',
'name' => 'max_width',
'type' => 'number',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'default_value' => 240,
'placeholder' => '',
'prepend' => '',
'append' => 'px',
'min' => 0,
'max' => '',
'step' => '',
),
array(
'key' => 'field_616a080825da3',
'label' => 'Close Button',
'name' => 'close_button',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_616a081525da4',
'label' => 'Close on Click',
'name' => 'close_on_click',
'type' => 'true_false',
'instructions' => 'Close popup whenever another place on the map is clicked.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 1,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_616a083525da5',
'label' => 'Close on Map Move',
'name' => 'close_on_map_move',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
),
'location' => array(
array(
array(
	'param' => 'post_type',
	'operator' => '==',
	'value' => 'mapster-wp-popup',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_6163d357655f4',
'title' => 'Popup',
'fields' => array(
array(
'key' => 'field_616a60c610c96',
'label' => 'Enable Popup',
'name' => 'enable_popup',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_616a145a4f1eb',
'label' => 'Popup Template',
'name' => 'popup_style',
'type' => 'post_object',
'instructions' => 'Create new popup styles in the "Popup Styles" section of Mapster WP Maps.',
'required' => 0,
'conditional_logic' => array(
	array(
		array(
			'field' => 'field_616a60c610c96',
			'operator' => '==',
			'value' => '1',
		),
	),
),
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'post_type' => array(
	0 => 'mapster-wp-popup',
),
'taxonomy' => '',
'allow_null' => 0,
'multiple' => 0,
'return_format' => 'object',
'ui' => 1,
),
array(
'key' => 'field_616a60fd2218f',
'label' => 'Interaction',
'name' => 'interaction',
'type' => 'select',
'instructions' => 'Choose how the popup will open.',
'required' => 0,
'conditional_logic' => array(
	array(
		array(
			'field' => 'field_616a60c610c96',
			'operator' => '==',
			'value' => '1',
		),
	),
),
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'choices' => array(
	'click' => 'Click',
	'hover' => 'Hover',
),
'default_value' => 'click',
'allow_null' => 0,
'multiple' => 0,
'ui' => 0,
'return_format' => 'value',
'ajax' => 0,
'placeholder' => '',
),
array(
'key' => 'field_6168d546268fb',
'label' => 'Popup',
'name' => 'popup',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => array(
	array(
		array(
			'field' => 'field_616a60c610c96',
			'operator' => '==',
			'value' => '1',
		),
	),
),
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6169fc8a6e649',
		'label' => 'Header Text',
		'name' => 'header_text',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_6169fcb16e64b',
		'label' => 'Featured Image',
		'name' => 'featured_image',
		'type' => 'image',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'return_format' => 'array',
		'preview_size' => 'medium',
		'library' => 'all',
		'min_width' => '',
		'min_height' => '',
		'min_size' => '',
		'max_width' => '',
		'max_height' => '',
		'max_size' => '',
		'mime_types' => '',
	),
	array(
		'key' => 'field_6169fc9c6e64a',
		'label' => 'Body Text',
		'name' => 'body_text',
		'type' => 'wysiwyg',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'tabs' => 'all',
		'toolbar' => 'full',
		'media_upload' => 0,
		'delay' => 0,
	),
	array(
		'key' => 'field_6169fcbc6e64c',
		'label' => 'Button Text',
		'name' => 'button_text',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_6169fda56e64f',
		'label' => 'Button Action',
		'name' => 'button_action',
		'type' => 'select',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'to-post' => 'To Feature Post',
			'to-link' => 'To URL',
			'do-nothing' => 'Do Nothing',
		),
		'default_value' => false,
		'allow_null' => 0,
		'multiple' => 0,
		'ui' => 0,
		'return_format' => 'value',
		'ajax' => 0,
		'placeholder' => '',
	),
	array(
		'key' => 'field_6169fddd6e650',
		'label' => 'Button URL',
		'name' => 'button_url',
		'type' => 'url',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_6169fda56e64f',
					'operator' => '==',
					'value' => 'to-link',
				),
			),
		),
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
	),
	array(
		'key' => 'field_6169fe006e651',
		'label' => 'Open Link in New Tab',
		'name' => 'open_link_in_new_tab',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => array(
			array(
				array(
					'field' => 'field_6169fda56e64f',
					'operator' => '==',
					'value' => 'to-post',
				),
			),
			array(
				array(
					'field' => 'field_6169fda56e64f',
					'operator' => '==',
					'value' => 'to-link',
				),
			),
		),
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 1,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
),
),
array(
'key' => 'field_61ca464a6f328',
'label' => 'Open Link on Click',
'name' => 'open_link_on_click',
'type' => 'true_false',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'message' => '',
'default_value' => 0,
'ui' => 1,
'ui_on_text' => '',
'ui_off_text' => '',
),
array(
'key' => 'field_61ca46666f32a',
'label' => 'Click Link',
'name' => 'click_link',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => array(
	array(
		array(
			'field' => 'field_61ca464a6f328',
			'operator' => '==',
			'value' => '1',
		),
	),
),
'wrapper' => array(
	'width' => '55',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_61ca465c6f329',
		'label' => 'URL',
		'name' => 'url',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_61ca46866f32b',
		'label' => 'Open Link in New Tab',
		'name' => 'open_link_in_new_tab',
		'type' => 'true_false',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 1,
		'ui' => 1,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
),
),
),
'location' => array(
array(
array(
	'param' => 'post_type',
	'operator' => '==',
	'value' => 'mapster-wp-location',
),
),
array(
array(
	'param' => 'post_type',
	'operator' => '==',
	'value' => 'mapster-wp-line',
),
),
array(
array(
	'param' => 'post_type',
	'operator' => '==',
	'value' => 'mapster-wp-polygon',
),
),
),
'menu_order' => 1,
'position' => 'acf_after_title',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
));

endif;		
?>
